### ISSUE TITLE
BoF at the European Galaxy Days

### ISSUE THREAD

**Issue by bgruening** [usegalaxy-eu/environmental_impact#7]
Agenda: https://docs.google.com/document/d/1krw121K1vHkxnHKcm4qKQfBNXjagQm_j_6C1mdhjB2Q/edit?usp=sharing

ToDo for Bjoern:

* get the energy mix from the compute center (Freiburg)
  * interval of 15min to 1h
  * maybe even the price

**Comment by bgruening** [comment]
https://docs.google.com/document/d/1IuOFMh9_70taR0sPzBpx2_ibEwpZn5GhkYrRaeTuDKs/edit

**Comment by sanjaysrikakulam** [comment]
ToDo for Sanjay:
1. For every job:
	1. time start (including date), time end (including date), requested CPU, requested mem, available CPU, available mem, tool info (tool name, version number, tool link, galaxy version), available gpu, cgroup outputs on the consumed resource per job, interactive tool or not info 
2. Server age, server model, CPU model
3. Theoretical capacity on how many servers were available for Galaxy over the period (talk to RZ, and maybe we can get this info from the OpenStack DB)
